---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shirui.
--- DateTime: 2025/1/21 下午3:00
---

AttrRulesOfSuccession = AttrRulesOfSuccession and nil or {
    _modeType = "White",
    _defaultFactor = 1,
    _list = { },
    _curRules = { },
}

function AttrRulesOfSuccession.SetListItem(attrType, factor)
    self._list[attrType] = factor
end

function AttrRulesOfSuccession.Reset()
    self._modeType = "White"
    self._defaultFactor = 1
    self._list = { }
    self._curRules = { }
end

function AttrRulesOfSuccession.SetRules(rule)
    self._curRule = self.Rule[rule]

    if self._curRule == nil then
        CS.UnityEngine.Debug.LogError("找不到对应继承规则 " .. rule)
        return
    end
end

--是否在名单上
function AttrRulesOfSuccession.IsInList(attrType)
    if self._curRule == nil then
        CS.UnityEngine.Debug.LogError("规则为空")
        return false
    end

    if self._modeType == "Black" then
        return self._list[attrType] == nil
    else
        return self._list[attrType] ~= nil
    end
end

--获取继承数据
function AttrRulesOfSuccession.Succession(rule, attrType, attrValue, param)
    if not self.IsInList(attrType) then
        return 0
    end
    
    
end


AttrRulesOfSuccession.Rule = {

    exampleBlacklist = function(param)
        --设置模式，黑名单或白名单，默认白名单模式
        self._modeType = "Black"
        -- self._modeType = "White"

        self:Succession(EAttrType.Attack,0.5 * param)

    end,

    exampleWhitelist = function()
        --设置模式，黑名单或白名单，默认白名单模式
        self._modeType = "White"
        -- self._modeType = "White"

        self:SetListItem()

    end,
}