---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shirui.
--- DateTime: 2024/8/27 下午3:29
---




local DamageFormula = {
    ["normalAttack"] = function()

    end,
    
    [2] = function()

    end,
    
    [3] = function()

    end,
}

