---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shirui.
--- DateTime: 2024/8/27 下午3:20
---

local DamageAdditionalFunc =
{
    [1] = function(attacker, target, damageInfo, addiParam)
        if( attacker.hasTag(adddiParam[1]))
         return addiParam[2]
        end
    end,
    
    [2] = function() 
        
    end
    
}