---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shirui.
--- DateTime: 2024/8/27 下午3:23
---
local DamageMultiplierFunc = {
    [1] = function()

    end,

    [2] = function()

    end
}